### ISSUE TITLE
TODO for release

### ISSUE THREAD

**Issue by onebone** [chalkpe/MDT#1]
# Not yet
- [ ] Add easter egg ʕ•̀ω•́ʔ✧
- [ ] Implement loading mod (by ProjectImporter class)
- [ ] Open .mod file by MDT in other app
# Work in progress
# Done
- [x] Add right-side button in list item
- [x] Show patch's status (included or excluded)
- [x] Make delete button that is delete project in WorkspaceActivity
- [x] Add Patch overlap checking
- [x] Workspace sort list for every changes
- [x] ~~Add TODO~~ `(Replaced to Memo)`
- [x] ~~Make space to write comment for brief patch~~ `(Cancelled)`
- [x] Prevent exporting when patches are overlapped
- [x] Add warning message that is saying cannot change project name later
- [x] Add export option (release or debug)
- [x] ~~Better JSONException handling~~ `(Replaced to checking file is empty)`
- [x] ~~Add Big Endian write option~~ `(Replaced to Unicode string option)`
- [x] Function viewer for disassembled text
- [x] GC for workspace
- [x] Redesign SettingsActivity (use Preference)
- [x] Move license information to InformationActivity
- [x] ~~Add HelpActivity~~ `(Not needed)`
